# kubetpl:syntax:$
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cabot-ingress
  namespace: cabot
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ${HOST}
    secretName: cabot-tls
  rules:
  - host: ${HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: cabot-web
          servicePort: 5000
